# Generated by Django 5.2 on 2025-09-02 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Punicoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=100)),
                ('id_punido', models.IntegerField()),
                ('id_dc', models.IntegerField()),
                ('temp_ban', models.IntegerField()),
                ('link_evid', models.URLField()),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='denuncias.motivos')),
            ],
        ),
    ]
