# Generated by Django 5.2 on 2025-09-02 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Motivos',
            new_name='Motivo',
        ),
        migrations.RenameModel(
            old_name='Punicoes',
            new_name='Punições',
        ),
    ]
