# Generated by Django 5.2 on 2025-09-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0002_rename_motivos_motivo_rename_punicoes_punições'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
    ]
