# Generated by Django 5.2 on 2025-09-02 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0003_vares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punições',
            name='nick_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='denuncias.vares'),
        ),
    ]
