# Generated by Django 5.2 on 2025-09-04 16:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0004_alter_punições_nick_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='punições',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='punições',
            name='id_dc',
            field=models.IntegerField(verbose_name='ID DC'),
        ),
        migrations.AlterField(
            model_name='punições',
            name='id_punido',
            field=models.IntegerField(verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='punições',
            name='link_evid',
            field=models.URLField(verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='punições',
            name='temp_ban',
            field=models.IntegerField(verbose_name='Tempo'),
        ),
    ]
