# Generated by Django 5.2 on 2025-09-04 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0005_punições_data_alter_punições_id_dc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='punições',
            old_name='data',
            new_name='created',
        ),
    ]
