# Generated by Django 5.2 on 2025-09-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0007_acoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acoes',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
