# Generated by Django 5.2 on 2025-10-03 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0008_alter_acoes_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='punições',
            name='codigo_tx',
            field=models.CharField(blank=True, null=True, verbose_name='Codigo-TX'),
        ),
        migrations.AlterField(
            model_name='punições',
            name='nick_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='denuncias.vares', verbose_name='Nome Var'),
        ),
        migrations.AlterField(
            model_name='punições',
            name='temp_ban',
            field=models.CharField(verbose_name='Tempo'),
        ),
    ]
