# Generated by Django 5.2 on 2025-10-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0009_punições_codigo_tx_alter_punições_nick_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punições',
            name='codigo_tx',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo-TX'),
        ),
        migrations.AlterField(
            model_name='punições',
            name='temp_ban',
            field=models.CharField(max_length=50, verbose_name='Tempo'),
        ),
    ]
