# Generated by Django 5.2 on 2025-09-01 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='var_registro',
            old_name='id_var',
            new_name='id_denunciante',
        ),
    ]
