# Generated by Django 5.2 on 2025-09-01 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0002_rename_id_var_var_registro_id_denunciante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='var_registro',
            old_name='id_denunciante',
            new_name='id_denunciado',
        ),
    ]
